version: "2"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:3
  web:
    build: .
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
  celery:
    build: .
    command: celery -A report_builder_demo worker -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    links:
      - db
      - redis
    environment:
      C_FORCE_ROOT: "true"
    volumes:
      - .:/code
  app:
    build: ./js
    command: sh -c "yarn start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./js:/home/node/app

      # Exclude directories from bind mounts.
      - ./js/node_modules/
      - node_modules:/home/node/app/node_modules

    depends_on:
      - web

volumes:
  node_modules:
